### ISSUE TITLE
Get entities from text

### ISSUE THREAD

**Issue by wadhwasahil** [studio-ousia/ntee#2]
Hi 

Just want to know if there is a method to get entities given a text in the code?

Thanks

**Comment by ikuyamada** [comment]
The code does not have such method. Please compute the text vector using `get_text_vector()` and search the nearest neighbors in the `entity_embedding` matrix.

**Comment by wadhwasahil** [comment]
Thanks. But @ikuyamada, in the k-nearest neighbour, how can we choose k if want we to extract almost all the entities present in the text and don't leave any?

**Comment by ikuyamada** [comment]
I might misunderstand your question.  If you want to detect entities that appear in the document, you need to perform entity linking. The code in this repository does not currently have such functionality.

**Comment by wadhwasahil** [comment]
Oh does that involve candidate generation and entity disambiguation as mentioned in the paper?

**Comment by ikuyamada** [comment]
This repository does not currently include code related to entity linking. Please use other entity linking systems to achieve your goal.

**Comment by wadhwasahil** [comment]
Correct me if I am wrong, so to get entities from a document, for e.g, "Apple delivered its iPhone with Tim Cook as its ceo", I need to follow below steps -
1. Find relevant entities - Apple, iPhone and Tim Cook. It can be done by finding entities from the lookup table of entities and doing a string search in the document. Take the longest length string as entity - for example Time, Cook and Tim Cook can be present in the lookup table, but we take Tim Cook.
2. Generate candidates for each entity found in step 1.
3. Disambiguate each entity to its correct link in wikipedia.

Please let me know if I on the right track.

Thanks a lot for your time and effort.

**Comment by ikuyamada** [comment]
To implement entity linking, we generally need a dictionary that maps entity names to possible referent entities. Of course, you can construct a dictionary using the titles of the entities.
However, this repository is not for entity linking, please refer to the other papers for details. Thanks.
